services:
  twitter-scraper:
    container_name: tweet_notify
    build:
      context: .
      args:
        - BROWSER=chromium
    restart: always
    environment:
      - PICKLE=1
    volumes:
      - ./history:/etc/scrapy/history