services:
  twitter-scraper:
    container_name: tweet_notify
    build:
      context: .
    restart: always
    environment:
      - PICKLE=1
      - BRIDGE=https://bridge.easter.fr/
    volumes:
      - ./history:/etc/tweet/history